package com.example.dynamodbtest.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.dynamodbtest.models.dto.MovieDetailDTO;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import org.springframework.data.annotation.Id;

@Data
@DynamoDBTable(tableName = "movies")
public class MovieDetail {

    @Id
    @JsonIgnore
    @DynamoDBIgnore
    private MovieDetailId movieDetailId;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return movieDetailId != null ? movieDetailId.getId() : null;
    }

    public void setId(String id) {
        if (movieDetailId == null)
            movieDetailId = new MovieDetailId();
        movieDetailId.setId(id);
    }

    @DynamoDBRangeKey(attributeName = "year_released")
    public String getYear() {
        return movieDetailId != null ? movieDetailId.getYear() : null;
    }

    public void setYear(String year) {
        if (movieDetailId == null)
            movieDetailId = new MovieDetailId();
        movieDetailId.setYear(year);
    }

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "genre")
    private String genre;

    @DynamoDBAttribute(attributeName = "country")
    private String country;

    @DynamoDBAttribute(attributeName = "duration")
    private Integer duration;

    @DynamoDBAttribute(attributeName = "language")
    private String language;

    public static MovieDetail parseMovieDetail(MovieDetailDTO movieDetailDTO) {
        MovieDetail movieDetail = new MovieDetail();
        movieDetail.setId(movieDetailDTO.getId());
        movieDetail.setYear(movieDetailDTO.getYear());
        movieDetail.setTitle(movieDetailDTO.getTitle());
        movieDetail.setGenre(movieDetailDTO.getGenre());
        movieDetail.setCountry(movieDetailDTO.getCountry());
        movieDetail.setDuration(movieDetailDTO.getDuration());
        movieDetail.setLanguage(movieDetailDTO.getLanguage());
        return movieDetail;
    }
}